const myFakeReviews = [
  {
    id: 13743,
    client_id: 82653,
    accueillant_id: 7871,
    prenom: 'CLAUDE',
    nom: 'BONNEFOY',
    date: '2020-06-22 17:08:45',
    message: 'Bel accueil Bel emplacement sur herbe De bon produits la tome est à tomber Eau Électricité. Je recommande.',
    note_accueil: 5,
    note_aire: 5,
    accueillant_ville: 'DŒUIL SUR LE MIGNON',
    accueillant_code_postal: '17330',
    accueillant_nom: 'Denis Blusseau',
    accueillant_nom_propriete: null,
  },
  {
    id: 13717,
    client_id: 174070,
    accueillant_id: 1942,
    prenom: 'Vincent',
    nom: 'Rouret',
    date: '2020-06-21 09:27:35',
    message: 'Très bien situé et pratique à 2km de st Pierre et 3km de la cotinnière',
    note_accueil: 5,
    note_aire: 5,
    accueillant_ville: "SAINT PIERRE D'OLÉRON",
    accueillant_code_postal: '17310',
    accueillant_nom: 'Christophe Vincent',
    accueillant_nom_propriete: 'Vignoble Vincent',
  },
  {
    id: 7,
    client_id: 48543,
    accueillant_id: 1889,
    prenom: 'Luc & Anne',
    nom: 'DE SCHRYVER BERGHMANS',
    date: '2014-06-02 00:42:21',
    message: 'Excellent accueil ! Du calme, de la tranquillit&eacute;. A conseiller !',
    note_accueil: 5,
    note_aire: 4,
    accueillant_ville: 'CORBEILLES',
    accueillant_code_postal: '45490',
    accueillant_nom: 'Anne-Marie & Michel Fouquin',
    accueillant_nom_propriete: 'Ferme La Champagne',
  },
];

export default myFakeReviews;
